name: Build Magic Frida Server
on:
  workflow_dispatch: # 允许你手动点击 "Run workflow" 按钮触发

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1.0.6
        with:
          ndk-version: r25b

      - name: Set up Python 3.9
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          sudo apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get install -y \
            build-essential tree ninja-build gcc-multilib g++-multilib \
            lib32stdc++-9-dev flex bison ruby ruby-dev python3-requests \
            python3-setuptools python3-dev python3-pip libc6-dev libc6-dev-i386
          sudo gem install fpm -v 1.11.0 --no-document
          python3 -m pip install lief graphlib

      - name: Clone and Patch Frida
        shell: bash
        run: |
          # 这一步下载原版 frida 并应用所有 strongR-frida 的反检测补丁
          export ANDROID_NDK_ROOT=${{ steps.setup-ndk.outputs.ndk-path }}
          git clone --recurse-submodules https://github.com/frida/frida
          cd frida
          for path in ../Patchs/strongR-frida/*
          do
            name=$(basename $path)
            real=$(realpath $path)
            echo "Applying patches in $real to frida/subprojects/$name"
            cd subprojects/$name
            git am ../../../Patchs/strongR-frida/$name/*.patch || true
            cd ../..
          done
          
          # 我们只需要 arm64 架构的 server (目前市面上 99% 手机都是 arm64)
          # 如果你需要别的架构，可以把 "android-arm64" 改成 "android-arm android-arm64 android-x86 android-x86_64"
          ARCHES="android-arm64"
          for ARCH in $ARCHES
          do
            mkdir build-$ARCH
            cd build-$ARCH
            ../frida/configure --host=$ARCH
            make
            cd ..
          done

      - name: Prepare Final Output
        shell: bash
        run: |
          # 把编译好的核心二进制文件提出来，准备打包
          mkdir -p magic_frida_output
          cp frida/build-android-arm64/subprojects/frida-core/server/frida-server magic_frida_output/hluda-server-arm64
          # 还可以加上 gadget 或 inject，如果需要的话
          # cp frida/build-android-arm64/subprojects/frida-core/lib/gadget/frida-gadget.so magic_frida_output/hluda-gadget-arm64.so

      - name: Upload Artifacts (ZIP)
        uses: actions/upload-artifact@v4
        with:
          name: Magic-Frida-Server-Arm64
          path: magic_frida_output/
